# Generated by Django 5.0.6 on 2024-07-04 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_new', models.BooleanField(default=True)),
                ('avarage_price', models.FloatField(default=0)),
                ('product', models.ManyToManyField(related_name='users', to='product.product')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
