# Generated by Django 5.0.6 on 2024-07-04 18:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_rename_styles_product_style'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('count', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='category',
            old_name='style',
            new_name='styles',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='style',
            new_name='styles',
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='HistoryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('styles', models.ManyToManyField(related_name='history_categories', to='product.historystyle')),
            ],
        ),
        migrations.CreateModel(
            name='ShoppingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories', models.ManyToManyField(related_name='shopping_histories', to='product.historycategory')),
            ],
        ),
    ]
